In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
# programme to find all the headers from Wikipedia

In [3]:
head = []

In [4]:
header = requests.get("https://en.wikipedia.org/wiki/Main_Page")
bs = BeautifulSoup(header.content,'html.parser')
wiki = bs.find_all(['h1','h2','h3','h4','h5','h6'])
for i in wiki:
    h1 = (i.text).replace('\n','')
    head.append(h1)

In [5]:
head

['Main Page',
 "From today's featured article",
 'Did you know\xa0...',
 'In the news',
 'On this day',
 "Today's featured picture",
 'Other areas of Wikipedia',
 "Wikipedia's sister projects",
 'Wikipedia languages',
 'Navigation menu',
 'Personal tools',
 'Namespaces',
 'Variantsexpandedcollapsed',
 'Views',
 'Moreexpandedcollapsed',
 'Search',
 'Navigation',
 'Contribute',
 'Tools',
 'Print/export',
 'In other projects',
 'Languages']

In [6]:
#programme to display IMDB's top 100 movies data

In [7]:
import pandas as pd

In [8]:
url = "https://www.imdb.com/list/ls091520106/"
page = requests.get(url)

In [9]:
soup = BeautifulSoup(page.content,'html.parser')

In [10]:
movie_name = []
year = []
rating = []

In [11]:
movie = soup.find_all('div',class_ = "lister-item-content")
for store in movie:
    movies = store.h3.a.text
    movie_name.append(movies)
    
    year_of_release = store.h3.find('span', class_ = 'lister-item-year text-muted unbold').text.replace('(','').replace(')','')
    year.append(year_of_release)
    
    Rating = store.find('span',class_ = 'ipl-rating-star__rating').text.replace('\n','')
    rating.append(Rating)

In [12]:
df = pd.DataFrame({ 'Name' : movie_name , 'Year_of_release' : year , 'Rating' : rating})
df

                                   Name Year_of_release Rating
0              The Shawshank Redemption            1994    9.3
1                         The Godfather            1972    9.2
2                The Godfather: Part II            1974      9
3                       The Dark Knight            2008      9
4                          12 Angry Men            1957      9
..                                  ...             ...    ...
95                   North by Northwest            1959    8.3
96                   A Clockwork Orange            1971    8.3
97                               Snatch            2000    8.3
98  Le fabuleux destin d'Amélie Poulain            2001    8.3
99                              The Kid            1921    8.3

[100 rows x 3 columns]

In [13]:
# programme to display IMDB'S Top 100 Indian movies

In [14]:
url = 'https://www.imdb.com/list/ls056092300/'
page = requests.get(url)

In [15]:
soup = BeautifulSoup(page.content,'html.parser')

In [16]:
m = []
y = []
r = []

In [17]:
movie1 = soup.find_all('div', class_ = 'lister-item-content')
for data in movie1:
    m1 = data.h3.a.text
    m.append(m1)
    
    year1 = data.h3.find('span', class_ = 'lister-item-year text-muted unbold').text.replace('(','').replace(')','')
    y.append(year1) 
    
    rating1 = data.find('span', class_ ='ipl-rating-star__rating').text.replace('\n','')
    r.append(rating1)

In [18]:
df1 = pd.DataFrame({'Name' : m , 'Year_of_release' : y , 'Rating' : r})
df1

                                 Name Year_of_release Rating
0                     Ship of Theseus            2012    8.1
1                              Iruvar            1997    8.5
2                     Kaagaz Ke Phool            1959      8
3   Lagaan: Once Upon a Time in India            2001    8.1
4                     Pather Panchali            1955    8.4
..                                ...             ...    ...
95                        Apur Sansar            1959    8.5
96                        Kanchivaram            2008    8.1
97                    Monsoon Wedding            2001    7.4
98                              Black            2005    8.2
99                            Deewaar            1975    8.1

[100 rows x 3 columns]

In [19]:
# Python programme to scrape cricket ranking 
# a) top 10 ODI team

In [20]:
link = 'https://www.icc-cricket.com/rankings/mens/team-rankings/odi'
page = requests.get(link)

In [21]:
bs = BeautifulSoup(page.content,'html.parser')

In [22]:
team = []
t1 = bs.find_all('div',class_ = 'rankings-block__container full rankings-table')
for data in t1:
    t = data.text.replace('\n',' ')
    team.append(t)
print(team)

['    Pos  Team T   Matches M   Points P   Rating R      1   New Zealand NZ  17 2,054                              121                                  2   England ENG  32 3,793 119   3   Australia AUS  28 3,244 116   4   India IND  32 3,624 113   5   South Africa SA  25 2,459 98   6   Pakistan PAK  27 2,524 93   7   Bangladesh BAN  30 2,740 91   8   West Indies WI  30 2,523 84   9   Sri Lanka SL  32 2,657 83   10   Afghanistan AFG  17 1,054 62   11   Netherlands NED  7 336 48   12   Ireland IRE  25 1,145 46   13   Scotland SCO  10 452 45   14   Zimbabwe ZIM  20 764 38   15   Oman OMA  14 524 37   16   Nepal NEP  11 330 30   17   UAE UAE  9 190 21   18   United States USA  14 232 17   19   Namibia NAM  6 97 16   20   Papua New Guinea PNG  13 0 0    ']

In [23]:
# b) Top 100 ODI Batsmen

In [24]:
link = 'https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting'
page = requests.get(link)

In [25]:
bs = BeautifulSoup(page.content,'html.parser')

In [26]:
b1 = bs.find('table', class_ = 'table rankings-table')
b2 = b1.text.replace('\n', '')

In [27]:
print(b2)

PosPlayerTeamRatingCareer Best Rating                            1                        (0)Babar AzamPAK873                                873 v England, 13/07/2021                                                            2                                (0)Virat KohliIND844                                911 v England, 12/07/2018                                                            3                                (0)Rohit SharmaIND813                                885 v Sri Lanka, 06/07/2019                                                            4                                (0)Ross TaylorNZ801                                841 v Bangladesh, 05/06/2019                                                            5                                (0)Aaron FinchAUS779                                798 v England, 25/06/2019                                                            6                                (0)Jonny BairstowENG775                                796 v India, 26/03/2021                                                            7                                (0)David WarnerAUS762                                880 v Pakistan, 26/01/2017                                                            8                                (0)Shai HopeWI758                                808 v Bangladesh, 17/05/2019                                                            9                                (0)Kane WilliamsonNZ754                                799 v India, 09/07/2019                                                            10                                (0)Quinton de KockSA743                                813 v Sri Lanka, 10/03/2019                                                            11                                (0)Fakhar ZamanPAK741                                779 v England, 08/07/2021                                                            12                                (0)Joe RootENG740                                824 v Sri Lanka, 13/10/2018                                                            13                                (0)Mushfiqur RahimBAN723                                739 v Sri Lanka, 25/05/2021                                                            14                                (0)Imam-ul-HaqPAK717                                768 v South Africa, 02/04/2021                                                            15                                (0)Martin GuptillNZ707                                789 v South Africa, 01/03/2017                                                            16                                (0)Shikhar DhawanIND704                                813 v Pakistan, 23/09/2018                                                            17                                (0)Steve SmithAUS696                                752 v Pakistan, 22/01/2017                                                            18                                (0)Jason RoyENG687                                782 v Australia, 11/07/2019                                                            19                                (0)Glenn MaxwellAUS674                                735 v India, 20/01/2016                                                            20                                (0)Rassie van der DussenSA671                                689 v Sri Lanka, 02/09/2021                                                            21                                (0)Tamim IqbalBAN670                                737 v West Indies, 28/07/2018                                                            22                                (0)Alex CareyAUS669                                669 v West Indies, 26/07/2021                                                            23                                (0)Paul StirlingIRE658                                697 v Netherlands, 04/06/2021                                                            24                                (0)Ben StokesENG651                                694 v New Zealand, 14/07/2019                                                            25                                (0)Eoin MorganENG650                                720 v Afghanistan, 18/06/2019                                                            26                                (0)Shakib Al HasanBAN641                                692 v Pakistan, 05/07/2019                                                            27                                (0)Lokesh RahulIND636                                657 v England, 26/03/2021                                                            28                                (0)Tom LathamNZ624                                631 v Bangladesh, 23/03/2021                                                            29                                (0)Nicholas PooranWI615                                634 v Ireland, 12/01/2020                                                            30                                (0)David MillerSA615                                643 v Pakistan, 04/04/2021                                                            31                                (0)Jos ButtlerENG608                                741 v Bangladesh, 08/06/2019                                                            32                                (0)Shimron HetmyerWI607                                709 v India, 15/12/2019                                                            33                                (0)Janneman MalanSA605                                605 v Netherlands, 26/11/2021                                                            34                                (0)Haris SohailPAK594                                618 v Zimbabwe, 30/10/2020                                                            35                                (0)Henry NichollsNZ581                                596 v Bangladesh, 20/03/2021                                                            36                                (0)Kyle CoetzerSCO575                                647 v Ireland, 18/03/2018                                                            37                                (4)This player has moved up in the rankings since the previous rankings updateAqib IlyasOMA574                                578 v United States, 11/02/2020                                                            38                                (1)This player has moved down in the rankings since the previous rankings updateMahmudullahBAN571                                582 v Sri Lanka, 28/05/2021                                                            39                                (1)This player has moved down in the rankings since the previous rankings updateBrendan TaylorZIM569                                667 v New Zealand, 09/02/2012                                                            40                                (1)This player has moved down in the rankings since the previous rankings updateAvishka FernandoSL568                                591 v South Africa, 02/09/2021                                                            41                                (1)This player has moved down in the rankings since the previous rankings updateAndrew BalbirnieIRE568                                584 v South Africa, 13/07/2021                                                            42                                (0)Rahmat ShahAFG559                                625 v Sri Lanka, 17/09/2018                                                            43                                (0)Evin LewisWI558                                567 v Sri Lanka, 12/03/2021                                                            44                                (0)Litton DasBAN558                                573 v Zimbabwe, 06/03/2020                                                            45                                (0)Kedar JadhavIND552                                629 v Afghanistan, 22/06/2019                                                            46                                (0)Kusal PereraSL551                                582 v England, 29/06/2021                                                            47                                (0)Hardik PandyaIND548                                561 v England, 28/03/2021                                                            48                                (0)Sean WilliamsZIM545                                561 v Pakistan, 03/11/2020                                                            49                                (0)Sikandar RazaZIM542                                576 v Afghanistan, 22/10/2015                                                            50                                (0)Angelo MathewsSL542                                707 v England, 07/12/2014                                                            51                                (0)Danushka GunathilakaSL530                                554 v Bangladesh, 28/05/2021                                                            52                                (0)Imad WasimPAK525                                556 v Bangladesh, 05/07/2019                                                            53                                (0)Soumya SarkarBAN521                                671 v South Africa, 15/07/2015                                                            54                                (0)Kusal MendisSL518                                631 v Zimbabwe, 30/06/2017                                                            55                                (0)Marcus StoinisAUS517                                616 v India, 08/03/2019                                                            56                                (0)Colin de GrandhommeNZ507                                520 v Pakistan, 19/01/2018                                                            57                                (0)Najibullah ZadranAFG506                                518 v West Indies, 09/11/2019                                                            58                                (0)Sarfaraz AhmedPAK504                                581 v West Indies, 05/10/2016                                                            59                                (0)Calum MacLeodSCO500                                585 v England, 10/06/2018                                                            60                                (0)Hashmatullah ShaidiAFG498                                519 v India, 22/06/2019                                                            61                                (0)Marnus LabuschagneAUS498                                532 v India, 29/11/2020                                                            62                                (0)Jimmy NeeshamNZ495                                549 v Pakistan, 26/06/2019                                                            63                                (0)Niroshan DickwellaSL495                                518 v Bangladesh, 28/05/2021                                                            64                                (0)Mohammad NabiAFG494                                545 v Bangladesh, 28/09/2016                                                            65                                (0)Mitchell MarshAUS489                                641 v New Zealand, 06/12/2016                                                            66                                (0)Richard BerringtonSCO487                                491 v Oman, 28/09/2021                                                            67                                (0)Kariyawasa AsalankaSL484                                484 v South Africa, 07/09/2021                                                            68                                (0)William PorterfieldIRE484                                539 v UAE, 12/03/2018                                                            69                                (0)Asghar AfghanAFG479                                483 v West Indies, 11/11/2019                                                            70                                (0)Harry TectorIRE477                                477 v Zimbabwe, 13/09/2021                                                            71                                (0)Assad ValaPNG476                                476 v Oman, 01/10/2021                                                            72                                (0)Craig ErvineZIM476                                524 v Afghanistan, 18/10/2015                                                            73                                (0)Aiden MarkramSA476                                485 v Sri Lanka, 04/09/2021                                                            74                                (0)Heinrich KlaasenSA474                                499 v Australia, 07/03/2020                                                            75                                (0)Dhananjaya de SilvaSL473                                482 v England, 01/07/2021                                                            76                                (0)Shreyas IyerIND472                                513 v New Zealand, 11/02/2020                                                            77                                (0)Muhammad UsmanUAE471                                478 v Ireland, 08/01/2021                                                            78                                (0)George MunseySCO464                                464 v Oman, 02/10/2021                                                            79                                (0)Mitchell SantnerNZ460                                502 v England, 10/03/2018                                                            80                                (0)Temba BavumaSA460                                467 v Sri Lanka, 02/09/2021                                                            81                                (0)Jason HolderWI446                                455 v Australia, 22/07/2021                                                            82                                (0)Andile PhehlukwayoSA440                                450 v Pakistan, 07/04/2021                                                            83                                (0)Ravindra JadejaIND434                                552 v West Indies, 08/10/2014                                                            84                                (0)Mithun AliBAN433                                452 v New Zealand, 23/03/2021                                                            85                                (0)Rashid KhanAFG432                                477 v Ireland, 10/03/2019                                                            86                                (0)Lahiru ThirimanneSL429                                599 v West Indies, 04/11/2015                                                            87                                (0)Rishabh PantIND426                                432 v England, 28/03/2021                                                            88                                (0)Dasun ShanakaSL424                                424 v South Africa, 07/09/2021                                                            89                                (0)Matthew WadeAUS424                                553 v Pakistan, 15/01/2017                                                            90                                (0)Rovman PowellWI419                                456 v India, 24/10/2018                                                            91                                (0)Kieron PollardWI416                                602 v Zimbabwe, 24/02/2013                                                            92                                (0)Gulbadin NaibAFG415                                440 v Ireland, 28/02/2018                                                            93                                (0)Mohammad RizwanPAK414                                426 v Australia, 29/03/2019                                                            94                                (0)Curtis CampherIRE412                                418 v South Africa, 16/07/2021                                                            95                                (0)Dinesh ChandimalSL409                                667 v Australia, 02/03/2012                                                            96                                (2)This player has moved up in the rankings since the previous rankings updateZeeshan MaqsoodOMA407                                407 v Namibia, 27/11/2021                                                            97                                (1)This player has moved down in the rankings since the previous rankings updateMax O'DowdNED406                                406 v South Africa, 26/11/2021                                                            98                                (1)This player has moved down in the rankings since the previous rankings updateMatthew CrossSCO405                                427 v Oman, 18/08/2019                                                            99                                (0)Moeen AliENG404                                522 v West Indies, 27/09/2017                                                            100                                (0)Chris WoakesENG403                                481 v Australia, 26/01/2018

In [28]:
# c) top 100 ODI bowlers

In [29]:
url = 'https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling'
page = requests.get(url)

In [30]:
bs = BeautifulSoup(page.content,'html.parser')

In [31]:
bow1 = bs.find('table', class_ = 'table rankings-table')

In [32]:
bow2 = bow1.text.replace('\n', ' ')
print(bow2)

   Pos Player Team Rating Career Best Rating                                   1                            (0)            Trent Boult       NZ    737                                     770 v West Indies, 22/06/2019                                                                       2                                    (0)     Josh Hazlewood    AUS  709                                  733 v England, 26/01/2018                                                                   3                                    (0)     Mujeeb Ur Rahman    AFG  708                                  712 v Ireland, 24/01/2021                                                                   4                                    (0)     Chris Woakes    ENG  700                                  711 v Sri Lanka, 04/07/2021                                                                   5                                    (0)     Mehedi Hasan    BAN  692                                  725 v Sri Lanka, 25/05/2021                                                                   6                                    (0)     Matt Henry    NZ  691                                  691 v Bangladesh, 26/03/2021                                                                   7                                    (0)     Jasprit Bumrah    IND  679                                  841 v West Indies, 01/11/2018                                                                   8                                    (0)     Mitchell Starc    AUS  652                                  783 v New Zealand, 29/03/2015                                                                   9                                    (0)     Shakib Al Hasan    BAN  650                                  717 v Zimbabwe, 05/11/2009                                                                   10                                    (0)     Kagiso Rabada    SA  643                                  724 v England, 29/05/2017                                                                   11                                    (0)     Mustafizur Rahman    BAN  640                                  695 v West Indies, 14/12/2018                                                                   12                                    (0)     Pat Cummins    AUS  636                                  729 v Pakistan, 12/06/2019                                                                   13                                    (0)     Shaheen Afridi    PAK  630                                  637 v England, 10/07/2021                                                                   14                                    (0)     Mohammad Amir    PAK  628                                  663 v Sri Lanka, 02/10/2019                                                                   15                                    (0)     Rashid Khan    AFG  626                                  806 v Pakistan, 21/09/2018                                                                   16                                    (0)     Adam Zampa    AUS  625                                  625 v West Indies, 26/07/2021                                                                   17                                    (0)     Bhuvneshwar Kumar    IND  621                                  657 v West Indies, 17/10/2014                                                                   18                                    (0)     Lachlan Ferguson    NZ  619                                  668 v West Indies, 22/06/2019                                                                   19                                    (0)     Jofra Archer    ENG  609                                  642 v Australia, 13/09/2020                                                                   20                                    (0)     Yuzvendra Chahal    IND  603                                  730 v New Zealand, 23/01/2019                                                                   21                                    (0)     Mohammad Nabi    AFG  596                                  653 v Zimbabwe, 26/02/2017                                                                   22                                    (0)     Mark Wood    ENG  594                                  615 v Afghanistan, 18/06/2019                                                                   23                                    (0)     Alzarri Joseph    WI  592                                  594 v Australia, 22/07/2021                                                                   24                                    (0)     Lungi Ngidi    SA  587                                  621 v Australia, 04/03/2020                                                                   25                                    (0)     Mitchell Santner    NZ  583                                  663 v England, 25/02/2018                                                                   26                                    (0)     Akila Dananjaya    SL  583                                  651 v England, 23/10/2018                                                                   27                                    (0)     Andy McBrine    IRE  579                                  579 v Zimbabwe, 13/09/2021                                                                   28                                    (0)     Mohammad Shami    IND  566                                  654 v Bangladesh, 19/03/2015                                                                   29                                    (0)     Kuldeep Yadav    IND  562                                  765 v New Zealand, 26/01/2019                                                                   30                                    (0)     Ravindra Jadeja    IND  550                                  738 v Zimbabwe, 01/08/2013                                                                   31                                    (0)     Tabraiz Shamsi    SA  546                                  562 v Sri Lanka, 07/09/2021                                                                   32                                    (0)     Sheldon Cottrell    WI  541                                  581 v Sri Lanka, 26/02/2020                                                                   33                                    (0)     Wanindu Hasaranga    SL  531                                  531 v South Africa, 07/09/2021                                                                   34                                    (0)     Ahmed Raza    UAE  531                                  531 v Ireland, 18/01/2021                                                                   35                                    (0)     Dushmantha Chameera    SL  525                                  538 v England, 29/06/2021                                                                   36                                    (0)     Mark Watt    SCO  519                                  529 v Papua New Guinea, 29/09/2021                                                                   37                                    (0)     Shadab Khan    PAK  517                                  607 v South Africa, 22/01/2019                                                                   38                                    (0)     Colin de Grandhomme    NZ  508                                  522 v India, 11/02/2020                                                                   39                                    (0)     Simi Singh    IRE  507                                  507 v Zimbabwe, 13/09/2021                                                                   40                                    (0)     David Willey    ENG  501                                  551 v Sri Lanka, 02/07/2016                                                                   41                                    (0)     Tim Southee    NZ  500                                  638 v England, 20/02/2015                                                                   42                                    (0)     Adil Rashid    ENG  497                                  687 v Sri Lanka, 20/10/2018                                                                   43                                    (0)     Ish Sodhi      496                                            44                                    (0)     Imad Wasim    PAK  488                                  570 v England, 19/05/2019                                                                   45                                    (0)     Hasan Ali    PAK  483                                  766 v New Zealand, 06/01/2018                                                                   46                                    (0)     Usman Khan    PAK  482                                  504 v Sri Lanka, 02/10/2019                                                                   47                                    (0)     Jhye Richardson    AUS  480                                  548 v Pakistan, 24/03/2019                                                                   48                                    (0)     Rohan Mustafa    UAE  477                                  477 v Ireland, 18/01/2021                                                                   49                                    (0)     Keshav Maharaj    SA  476                                  494 v Sri Lanka, 07/09/2021                                                                   50                                    (0)     Blessing Muzarabani    ZIM  470                                  470 v Ireland, 13/09/2021                                                                   51                                    (0)     Mashrafe Mortaza    BAN  469                                  653 v Zimbabwe, 23/01/2009                                                                   52                                    (0)     Mohammad Mohammad Saifuddin    BAN  468                                  496 v West Indies, 25/01/2021                                                                   53                                      (9) This player has moved up in the rankings since the previous rankings update     Zeeshan Maqsood    OMA  465                                  465 v Namibia, 27/11/2021                                                                   54                                      (1) This player has moved down in the rankings since the previous rankings update     Joshua Little    IRE  463                                  463 v Zimbabwe, 13/09/2021                                                                   55                                      (1) This player has moved down in the rankings since the previous rankings update     Jimmy Neesham    NZ  458                                  458 v Bangladesh, 26/03/2021                                                                   56                                      (1) This player has moved down in the rankings since the previous rankings update     Tendai Chatara    ZIM  458                                  562 v Ireland, 07/03/2015                                                                   57                                      (1) This player has moved down in the rankings since the previous rankings update     Andile Phehlukwayo    SA  456                                  613 v Pakistan, 30/01/2019                                                                   58                                      (1) This player has moved down in the rankings since the previous rankings update     Saqib Mahmood    ENG  454                                  454 v Pakistan, 13/07/2021                                                                   59                                      (1) This player has moved down in the rankings since the previous rankings update     Nuwan Pradeep    SL  453                                  506 v England, 13/10/2018                                                                   60                                      (1) This player has moved down in the rankings since the previous rankings update     Jason Holder    WI  451                                  486 v Sri Lanka, 10/03/2021                                                                   61                                      (1) This player has moved down in the rankings since the previous rankings update     Moeen Ali    ENG  449                                  629 v Australia, 24/06/2018                                                                   62                                      (1) This player has moved down in the rankings since the previous rankings update     Wahab Riaz    PAK  447                                  522 v England, 13/11/2015                                                                   63                                    (0)     Faheem Ashraf    PAK  445                                  477 v South Africa, 02/04/2021                                                                   64                                    (0)     Akeal Hosein    WI  443                                  443 v Australia, 26/07/2021                                                                   65                                    (0)     Tom Curran    ENG  436                                  443 v Sri Lanka, 04/07/2021                                                                   66                                    (0)     Safyaan Sharif    SCO  436                                  542 v England, 10/06/2018                                                                   67                                    (0)     Suranga Lakmal    SL  436                                  594 v Bangladesh, 25/01/2018                                                                   68                                    (0)     Ashton Agar    AUS  436                                  436 v West Indies, 26/07/2021                                                                   69                                    (0)     Taskin Ahmed    BAN  434                                  456 v Sri Lanka, 28/03/2017                                                                   70                                    (0)     Anrich Nortje    SA  429                                  436 v Sri Lanka, 02/09/2021                                                                   71                                    (0)     Sikandar Raza    ZIM  424                                  494 v UAE, 16/04/2019                                                                   72                                      (2) This player has moved up in the rankings since the previous rankings update     Bilal Khan    OMA  422                                  422 v Namibia, 27/11/2021                                                                   73                                      (1) This player has moved down in the rankings since the previous rankings update     Saurabh Netravalkar    USA  419                                  419 v Oman, 20/09/2021                                                                   74                                      (1) This player has moved down in the rankings since the previous rankings update     Josh Davey    SCO  418                                  436 v UAE, 15/12/2019                                                                   75                                    (0)     Kane Richardson    AUS  416                                  448 v India, 17/01/2020                                                                   76                                    (0)     Sean Williams    ZIM  413                                  474 v Sri Lanka, 30/06/2017                                                                   77                                    (0)     Ben Stokes    ENG  410                                  474 v New Zealand, 03/07/2019                                                                   78                                    (0)     Alasdair Evans    SCO  408                                  421 v England, 10/06/2018                                                                   79                                    (0)     Shardul Thakur    IND  405                                  411 v England, 28/03/2021                                                                   80                                    (0)     Craig Young    IRE  405                                  421 v South Africa, 16/07/2021                                                                   81                                    (0)     Dhananjaya de Silva    SL  401                                  412 v Bangladesh, 23/05/2021                                                                   82                                    (0)     Sandeep Lamichhane    NEP  400                                  400 v Oman, 19/09/2021                                                                   83                                    (0)     Rubel Hossain    BAN  400                                  514 v Pakistan, 01/12/2011                                                                   84                                    (0)     Gulbadin Naib    AFG  399                                  472 v Ireland, 21/05/2019                                                                   85                                    (0)     Chad Soper    PNG  397                                  399 v Oman, 26/09/2021                                                                   86                                    (0)     Hardik Pandya    IND  394                                  552 v South Africa, 16/02/2018                                                                   87                                    (0)     Mitchell Marsh    AUS  390                                  511 v New Zealand, 04/12/2016                                                                   88                                    (0)     Wayne Parnell    SA  387                                  550 v West Indies, 28/01/2015                                                                   89                                    (0)     Barry McCarthy    IRE  385                                  448 v West Indies, 09/01/2020                                                                   90                                    (0)     Fred Klaassen    NED  383                                  383 v South Africa, 26/11/2021                                                                   91                                    (0)     Nosaina Pokana    PNG  380                                  384 v Oman, 26/09/2021                                                                   92                                    (0)     Marcus Stoinis    AUS  377                                  426 v England, 25/06/2019                                                                   93                                    (0)     Michael Leask    SCO  374                                  382 v Papua New Guinea, 29/09/2021                                                                   94                                    (0)     Taijul Islam    BAN  374                                  397 v Zimbabwe, 06/03/2020                                                                   95                                    (0)     Mohammad Nawaz    PAK  370                                  376 v South Africa, 07/04/2021                                                                   96                                    (0)     Assad Vala    PNG  370              

In [33]:
# 4) python programme to scrape the Womens cricket team data
# a) Top 10 ODI teams of womens

In [34]:
url = 'https://www.icc-cricket.com/rankings/womens/team-rankings/odi'
page = requests.get(url)

In [35]:
bs1 = BeautifulSoup(page.content,'html.parser')

In [36]:
wo = []
w = bs1.find_all('span',class_ = 'u-hide-phablet')
for data in w:
    w1 = data.text
    wo.append(w1)
wo[0:10]

['Australia',
 'South Africa',
 'England',
 'India',
 'Bangladesh',
 'New Zealand',
 'West Indies',
 'Pakistan',
 'Ireland',
 'Sri Lanka']

In [37]:
matches = []
points = []
rating = []

In [38]:
for i in bs1.find_all('td', class_ = 'table-body__cell u-center-text'):
    rating.append(i.text)
for i in range(0,len(rating)-1,2):
    matches.append(rating[i])
    points.append(rating[i+1])

In [39]:
a = {'Womens_teams' : wo[0:10] , 'Matches' : matches , 'Points' : points , 'Rating' : rating[1:2:2]}
df = pd.DataFrame.from_dict(a,orient = 'index')
df = df.transpose()
df

   Womens_teams Matches Points Rating
0     Australia      19  2,307  2,307
1  South Africa      18  2,148   None
2       England      17  1,899   None
3         India       5    475   None
4    Bangladesh      19  1,668   None
5   New Zealand      19  1,658   None
6   West Indies      18  1,226   None
7      Pakistan       5    240   None
8       Ireland       5    233   None
9     Sri Lanka       7      0   None

In [40]:
#b) Top 100 Womens battting

In [41]:
url = 'https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting'
page = requests.get(url)

In [42]:
bs2 = BeautifulSoup(page.content,'html.parser')

In [43]:
batting = []
bat = bs2.find('table' , class_ = 'table rankings-table')
bat1 = bat.text.replace('\n','')
bat2 = bat1.split(' ')
bat2

['PosPlayerTeamRatingCareer',
 'Best',
 'Rating',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '1',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '(0)Lizelle',
 'LeeSA761',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '774',
 'v',
 'West',
 'Indies,',
 '07/09/2021',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '2',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '(0)Alyssa',
 'HealyAUS750',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '776',
 'v',
 'India,',
 '21/09/2021',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '3',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '(0)Mithali',
 'RajIND738',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '839',
 'v',
 'Australia,',
 '24/12/2004',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '4',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '(0)Tammy',
 'BeaumontENG728',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '791',
 'v',
 'India,',
 '27/06/2021',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '(0)Amy',
 'SatterthwaiteNZ717',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '756',
 'v',
 'Australia,',
 '02/03/2017',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '6',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '(0)Smriti',
 'MandhanaIND710',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '797',
 'v',
 'England,',
 '28/02/2019',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '7',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '(0)Meg',
 'LanningAUS699',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '834',
 'v',
 'New',
 'Zealand,',
 '24/02/2016',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '8',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '(0)Beth',
 'MooneyAUS690',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '690',
 'v',
 'India,',
 '26/09/2021',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 ...]

In [44]:
# c) Top 100 womens bowlers

In [45]:
url = 'https://www.icc-cricket.com/rankings/womens/player-rankings/odi/bowling'
page = requests.get(url)

In [46]:
bs3 = BeautifulSoup(page.content,'html.parser')

In [47]:
bowler = []
bow = bs3.find('table', class_ = 'table rankings-table')
bow.text.replace('\n','')

'PosPlayerTeamRatingCareer Best Rating                            1                        (0)Jess JonassenAUS760                                808 v New Zealand, 10/04/2021                                                            2                                (0)Jhulan GoswamiIND727                                796 v England, 28/02/2007                                                            3                                (0)Megan SchuttAUS717                                766 v West Indies, 11/09/2019                                                            4                                (0)Marizanne KappSA715                                749 v West Indies, 10/09/2021                                                            5                                (0)Sophie EcclestoneENG701                                701 v New Zealand, 26/09/2021                                                            6                                (0)Shabnim IsmailSA688                                743 v India, 07/03/2021                                                            7                                (0)Katherine BruntENG666                                796 v India, 03/02/2013                                                            8                                (0)Ayabonga KhakaSA643                                662 v West Indies, 10/09/2021                                                            9                                (0)Anya ShrubsoleENG598                                655 v Pakistan, 12/12/2019                                                            10                                (0)Kate CrossENG589                                589 v New Zealand, 26/09/2021                                                            11                                (0)Natalie SciverENG580                                580 v New Zealand, 26/09/2021                                                            12                                (0)Poonam YadavIND578                                680 v West Indies, 06/11/2019                                                            13                                (0)Ashleigh GardnerAUS577                                600 v Sri Lanka, 05/10/2019                                                            14                                (0)Leigh KasperekNZ574                                607 v England, 21/09/2021                                                            15                                (0)Hayley MatthewsWI571                                571 v Ireland, 23/11/2021                                                            16                                (0)Ellyse PerryAUS563                                719 v West Indies, 05/09/2019                                                            17                                (0)Dane van NiekerkSA562                                622 v Sri Lanka, 11/02/2019                                                            18                                (1)This player has moved up in the rankings since the previous rankings updateShikha PandeyIND561                                696 v South Africa, 11/10/2019                                                            19                                (1)This player has moved up in the rankings since the previous rankings updateLea TahuhuNZ557                                610 v Australia, 22/02/2019                                                            20                                (1)This player has moved up in the rankings since the previous rankings updateDeepti SharmaIND551                                650 v England, 22/02/2019                                                            21                                (3)This player has moved down in the rankings since the previous rankings updateNashra SandhuPAK550                                561 v Bangladesh, 21/11/2021                                                            22                                (0)Amelia KerrNZ540                                619 v England, 28/02/2021                                                            23                                (0)Rajeshwari GayakwadIND539                                575 v South Africa, 17/03/2021                                                            24                                (0)Georgia WarehamAUS502                                537 v India, 21/09/2021                                                            25                                (0)Anisa MohammedWI495                                704 v Australia, 11/11/2014                                                            26                                (0)Shakera SelmanWI482                                498 v Pakistan, 11/02/2019                                                            27                                (0)Stafanie TaylorWI473                                768 v New Zealand, 10/10/2013                                                            28                                (0)Ekta BishtIND466                                652 v England, 22/02/2019                                                            29                                (1)This player has moved up in the rankings since the previous rankings updateSophie DevineNZ442                                510 v India, 17/03/2009                                                            30                                (1)This player has moved down in the rankings since the previous rankings updateNida DarPAK439                                463 v Bangladesh, 04/03/2014                                                            31                                (1)This player has moved up in the rankings since the previous rankings updateKhadija Tul KubraBAN433                                442 v Zimbabwe, 15/11/2021                                                            32                                (8)This player has moved up in the rankings since the previous rankings updateAnam AminPAK428                                428 v Zimbabwe, 27/11/2021                                                            33                                (2)This player has moved down in the rankings since the previous rankings updateDiana BaigPAK424                                459 v West Indies, 18/07/2021                                                            34                                (1)This player has moved down in the rankings since the previous rankings updateInoka RanaweeraSL419                                542 v South Africa, 17/02/2019                                                            35                                (1)This player has moved down in the rankings since the previous rankings updateHannah RoweNZ412                                412 v England, 26/09/2021                                                            36                                (1)This player has moved down in the rankings since the previous rankings updateSalma KhatunBAN411                                411 v Pakistan, 21/11/2021                                                            37                                (1)This player has moved down in the rankings since the previous rankings updateRumana AhmedBAN410                                419 v South Africa, 11/02/2017                                                            38                                (1)This player has moved down in the rankings since the previous rankings updateNicola CareyAUS407                                407 v India, 26/09/2021                                                            39                                (1)This player has moved down in the rankings since the previous rankings updateTumi SekhukhuneSA400                                400 v West Indies, 19/09/2021                                                            40                                (1)This player has moved down in the rankings since the previous rankings updateShamilia ConnellWI400                                400 v Ireland, 23/11/2021                                                            41                                (0)Afy FletcherWI393                                527 v India, 06/11/2019                                                            42                                (0)Nahida AkterBAN387                                387 v Pakistan, 21/11/2021                                                            43                                (0)Sune LuusSA386                                480 v England, 18/07/2017                                                            44                                (0)Jahanara AlamBAN372                                385 v Zimbabwe, 13/11/2021                                                            45                                (0)Sophie MolineuxAUS365                                365 v India, 26/09/2021                                                            46                                (0)Masabata KlaasSA353                                400 v New Zealand, 27/01/2020                                                            47                                (0)Charlotte DeanENG351                                351 v New Zealand, 26/09/2021                                                            48                                (0)Jess KerrNZ349                                356 v England, 23/09/2021                                                            49                                (0)Holly HuddlestonNZ336                                464 v Ireland, 10/06/2018                                                            50                                (0)Udeshika PrabodhaniSL330                                370 v South Africa, 11/02/2019                                                            51                                (0)Hayley JensenNZ312                                312 v England, 26/09/2021                                                            52                                (0)Darcie BrownAUS304                                310 v India, 24/09/2021                                                            53                                (0)Sarah GlennENG296                                330 v New Zealand, 26/02/2021                                                            54                                (0)Celeste RaackIRE295                                295 v West Indies, 23/11/2021                                                            55                                (0)Heather KnightENG290                                405 v Sri Lanka, 12/11/2016                                                            56                                (0)Annabel SutherlandAUS280                                280 v India, 26/09/2021                                                            57                                (0)Panna GhoshBAN279                                303 v Pakistan, 04/11/2019                                                            58                                (0)Nadine KlerkSA269                                269 v West Indies, 19/09/2021                                                            59                                (15)This player has moved up in the rankings since the previous rankings updateSadia IqbalPAK265                                265 v Zimbabwe, 27/11/2021                                                            60                                (1)This player has moved down in the rankings since the previous rankings updateLeah PaulIRE253                                253 v West Indies, 23/11/2021                                                            61                                (14)This player has moved up in the rankings since the previous rankings updatePrecious MarangeZIM250                                250 v Pakistan, 27/11/2021                                                            62                                (16)This player has moved up in the rankings since the previous rankings updateFatima SanaPAK249                                249 v Zimbabwe, 27/11/2021                                                            63                                (3)This player has moved down in the rankings since the previous rankings updateTayla VlaeminckAUS249                                272 v Sri Lanka, 05/10/2019                                                            64                                (3)This player has moved down in the rankings since the previous rankings updateChloe-Lesleigh TryonSA249                                366 v New Zealand, 11/10/2016                                                            65                                (3)This player has moved down in the rankings since the previous rankings updateChamari AthapaththuSL247                                279 v South Africa, 17/02/2019                                                            66                                (3)This player has moved down in the rankings since the previous rankings updateEimear RichardsonIRE246                                361 v Pakistan, 22/08/2012                                                            67                                (1)This player has moved down in the rankings since the previous rankings updateJosephine NkomoZIM245                                275 v Ireland, 11/10/2021                                                            68                                (4)This player has moved down in the rankings since the previous rankings updateRosemary MairNZ238                                281 v Australia, 05/10/2020                                                            69                                (4)This player has moved down in the rankings since the previous rankings updateHarmanpreet KaurIND237                                280 v West Indies, 06/11/2019                                                            70                                (3)This player has moved down in the rankings since the previous rankings updateOshadi RanasingheSL230                                235 v Australia, 05/10/2019                                                            71                                (3)This player has moved down in the rankings since the previous rankings updateChinelle HenryWI228                                228 v Ireland, 23/11/2021                                                            72                                (3)This player has moved down in the rankings since the previous rankings updateMeghna SinghIND227                                227 v Australia, 26/09/2021                                                            73                                (3)This player has moved down in the rankings since the previous rankings updateAchini KulasuriyaSL226                                226 v Australia, 09/10/2019                                                            74                                (3)This player has moved down in the rankings since the previous rankings updateSugandika KumariSL225                                277 v India, 19/02/2016                                                            75                                (3)This player has moved down in the rankings since the previous rankings updateDeandra DottinWI225                                440 v Pakistan, 07/02/2019                                                            76                                (3)This player has moved down in the rankings since the previous rankings updateNondumiso ShangaseSA224                                224 v West Indies, 19/09/2021                                                            77                                (1)This player has moved down in the rankings since the previous rankings updateCara MurrayIRE222                                227 v Zimbabwe, 11/10/2021                                                            78                                (1)This player has moved down in the rankings since the previous rankings updateNonkululeko MlabaSA221                                277 v India, 07/03/2021                                                            79                                (0)Qiana JosephWI215                                219 v Pakistan, 14/11/2021                                                            80                                (0)Freya DaviesENG211                                216 v New Zealand, 16/09/2021                                                            81                                (0)Laura DelanyIRE210                                232 v Netherlands, 26/04/2011                                                            82                                (1)This player has moved up in the rankings since the previous rankings updateJane MaguireIRE206                                217 v Zimbabwe, 11/10/2021                                                            83                                (1)This player has moved up in the rankings since the previous rankings updateBismah MaroofPAK199                                327 v West Indies, 16/10/2015                                                            84                                (2)This player has moved down in the rankings since the previous rankings updateEsther MbofanaZIM196                                207 v Bangladesh, 15/11/2021                                                            85                                (0)Ama KanchanaSL194                                244 v Pakistan, 22/03/2018                                                            86                                (0)Mansi JoshiIND193                                222 v South Africa, 14/03/2021                                                            87                                (0)Tash FarrantENG191                                212 v New Zealand, 19/09/2021                                                            88                                This player has moved up in the rankings since the previous rankings updateLoreen TshumaZIM188                                188 v Pakistan, 27/11/2021                                                            89                                (1)This player has moved down in the rankings since the previous rankings updateSophie MacMahonIRE188                                192 v Zimbabwe, 11/10/2021                                                            90                                (0)Amy SatterthwaiteNZ187                                405 v West Indies, 06/07/2017                                                            91                                (2)This player has moved down in the rankings since the previous rankings updateLorraine PhiriZIM183                                187 v Bangladesh, 15/11/2021                                                            92                                (1)This player has moved down in the rankings since the previous rankings updateAaliyah AlleyneWI182                                185 v Pakistan, 14/11/2021                                                            93                                (5)This player has moved up in the rankings since the previous rankings updateUmaima SohailPAK179                                179 v Zimbabwe, 27/11/2021                                                            94                                (2)This player has moved down in the rankings since the previous rankings updateTahlia McGrathAUS178                                179 v India, 24/09/2021                                                            95                                (2)This player has moved down

In [48]:
# 6) programmeto scrape details of all posts coreymns.com

In [49]:
link = 'https://coreyms.com/'
page = requests.get(link)

In [50]:
bs4 = BeautifulSoup(page.content,'html.parser')

In [51]:
head = []
h1 = bs4.find_all('a', class_ = 'entry-title-link')
for data in h1:
    he = data.text
    head.append(he)
head

['Python Tutorial: Zip Files – Creating and Extracting Zip Archives',
 'Python Data Science Tutorial: Analyzing the 2019 Stack Overflow Developer Survey',
 'Python Multiprocessing Tutorial: Run Code in Parallel Using the Multiprocessing Module',
 'Python Threading Tutorial: Run Code Concurrently Using the Threading Module',
 'Update (2019-09-03)',
 'Python Quick Tip: The Difference Between “==” and “is” (Equality vs Identity)',
 'Python Tutorial: Calling External Commands Using the Subprocess Module',
 'Visual Studio Code (Windows) – Setting up a Python Development Environment and Complete Overview',
 'Visual Studio Code (Mac) – Setting up a Python Development Environment and Complete Overview',
 'Clarifying the Issues with Mutable Default Arguments']

In [52]:
date = []
d1 = bs4.find_all('time', class_ = 'entry-time')
for data in d1:
    da = data.text
    date.append(da)
date

['November 19, 2019',
 'October 17, 2019',
 'September 21, 2019',
 'September 12, 2019',
 'September 3, 2019',
 'August 6, 2019',
 'July 24, 2019',
 'May 1, 2019',
 'May 1, 2019',
 'April 24, 2019']

In [53]:
content = []
con1 = bs4.find_all('div', class_ = 'entry-content')
for data in con1:
    con = data.text.replace('\n','')
    content.append(con)
content

['In this video, we will be learning how to create and extract zip archives. We will start by using the zipfile module, and then we will see how to do this using the shutil module. We will learn how to do this with single files and directories, as well as learning how to use gzip as well. Let’s get started…',
 'In this Python Programming video, we will be learning how to download and analyze real-world data from the 2019 Stack Overflow Developer Survey. This is terrific practice for anyone getting into the data science field. We will learn different ways to analyze this data and also some best practices. Let’s get started…',
 'In this Python Programming video, we will be learning how to run code in parallel using the multiprocessing module. We will also look at how to process multiple high-resolution images at the same time using a ProcessPoolExecutor from the concurrent.futures module. Let’s get started…',
 'In this Python Programming video, we will be learning how to run threads concurrently using the threading module. We will also look at how to download multiple high-resolution images online using a ThreadPoolExecutor from the concurrent.futures module. Let’s get started…',
 'Hey everyone. I wanted to give you an update on my videos. I will be releasing videos on threading and multiprocessing within the next week. Thanks so much for your patience. I currently have a temporary recording studio setup at my Airbnb that will allow me to record and edit the threading/multiprocessing videos. I am going to be moving into my new house in 10 days and once I have my recording studio setup then you can expect much faster video releases. I really appreciate how patient everyone has been while I go through this move, especially those of you who are contributing monthly through YouTube ',
 'In this Python Programming Tutorial, we will be learning the difference between using “==” and the “is” keyword when doing comparisons. The difference between these is that “==” checks to see if values are equal, and the “is” keyword checks their identity, which means it’s going to check if the values are identical in terms of being the same object in memory. We’ll learn more in the video. Let’s get started…',
 'In this Python Programming Tutorial, we will be learning how to run external commands using the subprocess module from the standard library. We will learn how to run commands, capture the output, handle errors, and also how to pipe output into other commands. Let’s get started…',
 'In this Python Programming Tutorial, we will be learning how to set up a Python development environment in VSCode on Windows. VSCode is a very nice free editor for writing Python applications and many developers are now switching over to this editor. In this video, we will learn how to install VSCode, get the Python extension installed, how to change Python interpreters, create virtual environments, format/lint our code, how to use Git within VSCode, how to debug our programs, how unit testing works, and more. We have a lot to cover, so let’s go ahead and get started…VSCode on MacOS – https://youtu.be/06I63_p-2A4Timestamps for topics in this tutorial: Installation – 1:13 Python Extension – 5:48 Switching Interpreters – 10:04 Changing Color Themes – 12:35 VSCode Settings – 16:16 Set Default Python – 21:33 Using Virtual Environments – 25:10 IntelliSense – 29:45 Code Formatting – 32:13 Code Linting – 37:06 Code Runner Extension – 39:42 Git Integration – 47:44 Use Different Terminal – 51:07 Debugging – 58:45 Unit Testing – 1:03:25 Zen Mode – 1:09:55',
 'In this Python Programming Tutorial, we will be learning how to set up a Python development environment in VSCode on MacOS. VSCode is a very nice free editor for writing Python applications and many developers are now switching over to this editor. In this video, we will learn how to install VSCode, get the Python extension installed, how to change Python interpreters, create virtual environments, format/lint our code, how to use Git within VSCode, how to debug our programs, how unit testing works, and more. We have a lot to cover, so let’s go ahead and get started…VSCode on Windows – https://youtu.be/-nh9rCzPJ20Timestamps for topics in this tutorial: Installation – 1:11 Python Extension – 6:21 Switching Interpreters – 10:16 Changing Color Themes – 13:08 VSCode Settings – 17:12 Set Default Python – 22:24 Using Virtual Environments – 25:52 IntelliSense – 30:28 Code Formatting – 33:08 Code Linting – 38:01 Code Runner Extension – 40:45 Git Integration – 49:05 Debugging – 58:15 Unit Testing – 1:02:38 Zen Mode – 1:10:42 ',
 'In this Python Programming Tutorial, we will be clarifying the issues with mutable default arguments. We discussed this in my last video titled “5 Common Python Mistakes and How to Fix Them”, but I received many comments from people who were still confused. So we will be doing a deeper dive to explain exactly what is going on here. Let’s get started…']

In [54]:
url1 = []
for link in bs4.find_all('a'):
    print(link.get('href'))

https://coreyms.com/
https://coreyms.com/
https://www.youtube.com/user/schafer5
https://github.com/CoreyMSchafer
https://plus.google.com/+CoreySchafer44/posts
https://twitter.com/CoreyMSchafer
https://www.instagram.com/coreymschafer/
http://coreyms.com/feed/
https://coreyms.com/contact
http://coreyms.com/portfolio
https://coreyms.com/category/development
https://coreyms.com/category/development/python
https://coreyms.com/category/development/git
https://coreyms.com/category/development/terminal
https://coreyms.com/category/development/javascript
https://coreyms.com/category/development/wordpress
https://coreyms.com/category/web-design
https://coreyms.com/category/web-design/css
https://coreyms.com/category/diy
https://coreyms.com/category/diy/woodworking
https://coreyms.com/category/diy/home-improvement
https://coreyms.com/contributors
https://coreyms.com/support
https://coreyms.com/giveaway
https://coreyms.com/development/python/python-tutorial-zip-files-creating-and-extracting-zip-archives
https://coreyms.com/author/coreymschafer
https://coreyms.com/development/python/python-tutorial-zip-files-creating-and-extracting-zip-archives#respond
https://coreyms.com/category/development
https://coreyms.com/category/development/python
https://coreyms.com/tag/gzip
https://coreyms.com/tag/shutil
https://coreyms.com/tag/zip
https://coreyms.com/tag/zipfile
https://coreyms.com/development/python/python-data-science-tutorial-analyzing-the-2019-stack-overflow-developer-survey
https://coreyms.com/author/coreymschafer
https://coreyms.com/development/python/python-data-science-tutorial-analyzing-the-2019-stack-overflow-developer-survey#respond
https://coreyms.com/category/development
https://coreyms.com/category/development/python
https://coreyms.com/tag/data-analysis
https://coreyms.com/tag/data-science
https://coreyms.com/tag/stack-overflow
https://coreyms.com/development/python/python-multiprocessing-tutorial-run-code-in-parallel-using-the-multiprocessing-module
https://coreyms.com/author/coreymschafer
https://coreyms.com/development/python/python-multiprocessing-tutorial-run-code-in-parallel-using-the-multiprocessing-module#respond
https://coreyms.com/category/development
https://coreyms.com/category/development/python
https://coreyms.com/tag/asynchronous
https://coreyms.com/tag/concurrent-futures
https://coreyms.com/tag/multiprocessing
https://coreyms.com/tag/parallel
https://coreyms.com/tag/threading
https://coreyms.com/development/python/python-threading-tutorial-run-code-concurrently-using-the-threading-module
https://coreyms.com/author/coreymschafer
https://coreyms.com/development/python/python-threading-tutorial-run-code-concurrently-using-the-threading-module#respond
https://coreyms.com/category/development
https://coreyms.com/category/development/python
https://coreyms.com/tag/asynchronous
https://coreyms.com/tag/concurrency
https://coreyms.com/tag/multiprocessing
https://coreyms.com/tag/threading
https://coreyms.com/general/update-2019-09-03
https://coreyms.com/author/coreymschafer
https://coreyms.com/general/update-2019-09-03#respond
https://coreyms.com/category/general
https://coreyms.com/development/python/python-quick-tip-the-difference-between-and-is-equality-vs-identity
https://coreyms.com/author/coreymschafer
https://coreyms.com/development/python/python-quick-tip-the-difference-between-and-is-equality-vs-identity#respond
https://coreyms.com/category/development
https://coreyms.com/category/development/python
https://coreyms.com/tag/vs-is
https://coreyms.com/tag/equality
https://coreyms.com/tag/identity
https://coreyms.com/development/python/python-tutorial-calling-external-commands-using-the-subprocess-module
https://coreyms.com/author/coreymschafer
https://coreyms.com/development/python/python-tutorial-calling-external-commands-using-the-subprocess-module#respond
https://coreyms.com/category/development
https://coreyms.com/category/development/python
https://coreyms.com/tag/standard-library
https://coreyms.com/tag/subprocess
https://coreyms.com/development/python/visual-studio-code-windows-setting-up-a-python-development-environment-and-complete-overview
https://coreyms.com/author/coreymschafer
https://coreyms.com/development/python/visual-studio-code-windows-setting-up-a-python-development-environment-and-complete-overview#respond
https://coreyms.com/category/development
https://coreyms.com/category/development/python
https://coreyms.com/tag/development-environment
https://coreyms.com/tag/visual-studio-code
https://coreyms.com/tag/visual-studios
https://coreyms.com/tag/vs-code
https://coreyms.com/tag/vscode
https://coreyms.com/development/python/visual-studio-code-mac-setting-up-a-python-development-environment-and-complete-overview
https://coreyms.com/author/coreymschafer
https://coreyms.com/development/python/visual-studio-code-mac-setting-up-a-python-development-environment-and-complete-overview#respond
https://coreyms.com/category/development
https://coreyms.com/category/development/python
https://coreyms.com/tag/development-environment
https://coreyms.com/tag/visual-studio-code
https://coreyms.com/tag/visual-studios
https://coreyms.com/tag/vs-code
https://coreyms.com/tag/vscode
https://coreyms.com/development/python/clarifying-the-issues-with-mutable-default-arguments
https://coreyms.com/author/coreymschafer
https://coreyms.com/development/python/clarifying-the-issues-with-mutable-default-arguments#respond
https://coreyms.com/category/development
https://coreyms.com/category/development/python
https://coreyms.com/tag/common-errors
https://coreyms.com/tag/common-mistakes
https://coreyms.com/tag/functions
https://coreyms.com/tag/mutable-default-arguments
https://coreyms.com/
https://coreyms.com/page/2
https://coreyms.com/page/3
https://coreyms.com/page/17
https://coreyms.com/page/2
https://www.patreon.com/coreyms
https://www.amazon.com/gp/product/1449355730/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1449355730&linkCode=as2&tag=coreyms-20&linkId=2f9ceaf471d7d35f2c2657051780fc6f
https://www.amazon.com/gp/product/1491946008/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1491946008&linkCode=as2&tag=coreyms-20&linkId=39335cdc340fb7ce5bd51d59c57e7e54
https://www.amazon.com/gp/product/1593276036/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=1593276036&linkCode=as2&tag=coreyms-20&linkId=75ff844a147bc8cb5fb325608b286158
https://www.amazon.com/gp/product/0984782850/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0984782850&linkCode=as2&tag=coreyms-20&linkId=e2f7c21906426f17958a1d04718e7d02
https://www.amazon.com/gp/product/020161622X/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=020161622X&linkCode=as2&tag=coreyms-20&linkId=a2699f6b6cb5814da54f71140c52f2ca
https://www.amazon.com/gp/product/0201835959/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0201835959&linkCode=as2&tag=coreyms-20&linkId=c3de80ab4a4761f7634751cf323af13f
http://talkpython.fm/
http://shoptalkshow.com/
http://www.se-radio.net/
http://hanselminutes.com/
https://blog.codepen.io/radio/
http://www.dancarlin.com/hardcore-history-series/
http://www.billburr.com/podcast
http://www.samharris.org/podcast
http://www.startalkradio.net/shows-archive/
http://carasantamaria.com/podcast/
http://coreyms.com

In [55]:
# 7) python programme to scrape house details

In [56]:
url = 'https://www.nobroker.in/property/sale/bangalore/Electronic%20City?type=BHK4&searchParam=W3sibGF0IjoxMi44N%20DUyMTQ1LCJsb24iOjc3LjY2MDE2OTUsInBsYWNlSWQiOiJDaElKdy1GUWQ0cHNyanNSSGZkYXpnXzhYRW8%20iLCJwbGFjZU5hbWUiOiJFbGVjdHJvbmljIENpdHkifV0=&propertyAge=0&radius=2.0'
page = requests.get(url)

In [57]:
bs5 = BeautifulSoup(page.content,'html.parser')

In [58]:
house_title = []
ht = bs5.find_all('h2', class_ = 'heading-6 font-semi-bold nb__25Cl7')
for data in ht:
    ht1 = data.text
    house_title.append(ht1)
house_title

['4 BHK In Independent House  For Sale  In Hebbagodi ',
 '4 BHK In Independent House  For Sale  In Electronic City ',
 '4 BHK In Independent House  For Sale  In Electronics City Phase 1, Electronic City ',
 '4 BHK Flat  For Sale  In Electronic City ',
 '4 BHK Apartment  For Sale  In Nisarga Residency In Electronic City Phase Ii ',
 '4 BHK Flat  For Sale  In Sobha Silicon Oasis  In Hosa Road ',
 '4 BHK For Sale  In Daadys Garden In Electronic City ',
 '4 BHK Flat  For Sale  In , Electronic City ',
 '4 BHK Flat  For Sale  In Hosa Road, Parappana Agrahara ',
 '4 BHK In Independent House  For Sale  In Electronic City ',
 '4 BHK In Independent House  For Sale  In Electronic City ',
 '4 BHK Apartment  For Sale  In Gopalan Gardenia In Electronic City ',
 '4 BHK For Sale  In Gpr Royale In Gpr Royale ',
 '4 BHK Flat  For Sale  In Heena Enclave In Electronic City ',
 '4 BHK For Sale  In Deccan Palms Park In Electronic City ',
 '4 BHK In Independent House  For Sale  In Electronic City Phase Ii ']

In [59]:
Location = []
ln = bs5.find_all('div', class_ = 'nb__1EwQz')
for data in ln:
    loca = data.text
    Location.append(loca)
Location

['Independent House, Bangalore - Hosur Road, Near  National Public School',
 'Independent House, Shanthi Pura, Electronic City Phase II,Near Sallapuriyamma Temple Shanthipura',
 'Independent House, brand factory',
 'Standalone Building, YOUNG LIFE PG FOR LADIES, Konappana Agrahara, Electronic City, Bengaluru, Karnataka, India',
 'Nisarga Residency\xa0 Near Thali Resturant, Ananth Nagar, Electronic City Phase II, Bangalore, Karnataka, INDIA.',
 'Sobha Silicon Oasis Naganathapura, Rayasandra Bengaluru, Karnataka 560100 India',
 'Daadys Garden\xa0 Kammasandra Rd, Kammasandra, Electronic City, Bengaluru, Karnataka 560100, India',
 'Standalone Building, 16th Cross Road Neeladri Nagar, near by brand factory',
 'Standalone Building, 11th cross.anjanadri lay out',
 'Independent House, surya nagar face 1',
 'Independent House, Hosur Rd,Near Infosys Limited',
 'Gopalan Gardenia\xa0 Gopalan gardenia, Veerasandra Main Rd, Veer Sandra, Electronic City, Bengaluru, Karnataka 560100, India',
 '6th Cross',
 ' Neeladri Nagar,Near Pioneer Sun Blossom',
 'Deccan Palms Park\xa0 Deccan Palms Villas, Deccan Palms Road, Shree Ananth Nagar Layout, Glass Factory Layout, Electronic City, Bengaluru, Karnataka 560100, India',
 'Independent House, Industrial Area Near Tech Mahindra']

In [60]:
Area = []
ar = bs5.find_all('div', class_ ='nb__FfHqA')
for data in ar:
    ar1 = data.text
    Area.append(ar1)
Area

['1,800 sqft',
 '1,400 sqft',
 '2,000 sqft',
 '1,120 sqft',
 '2,000 sqft',
 '1,879 sqft',
 '2,600 sqft',
 '2,000 sqft',
 '3,000 sqft',
 '3,000 sqft',
 '1,200 sqft',
 '2,650 sqft',
 '3,100 sqft',
 '2,350 sqft',
 '3,000 sqft',
 '1,500 sqft']

In [61]:
df2 = pd.DataFrame({ 'House_title' : house_title, 'Location' : Location , 'Area' : Area})
df2

,House_title,Location,Area
0,4 BHK In Independent House For Sale In Hebba...,"Independent House, Bangalore - Hosur Road, Nea...","1,800 sqft"
1,4 BHK In Independent House For Sale In Elect...,"Independent House, Shanthi Pura, Electronic Ci...","1,400 sqft"
2,4 BHK In Independent House For Sale In Elect...,"Independent House, brand factory","2,000 sqft"
3,4 BHK Flat For Sale In Electronic City,"Standalone Building, YOUNG LIFE PG FOR LADIES,...","1,120 sqft"
4,4 BHK Apartment For Sale In Nisarga Residenc...,"Nisarga Residency Near Thali Resturant, Anant...","2,000 sqft"
5,4 BHK Flat For Sale In Sobha Silicon Oasis ...,"Sobha Silicon Oasis Naganathapura, Rayasandra ...","1,879 sqft"
6,4 BHK For Sale In Daadys Garden In Electronic...,"Daadys Garden Kammasandra Rd, Kammasandra, El...","2,600 sqft"
7,"4 BHK Flat For Sale In , Electronic City","Standalone Building, 16th Cross Road Neeladri ...","2,000 sqft"
8,"4 BHK Flat For Sale In Hosa Road, Parappana ...","Standalone Building, 11th cross.anjanadri lay out","3,000 sqft"
9,4 BHK In Independent House For Sale In Elect...,"Independent House, surya nagar face 1","3,000 sqft"
10,4 BHK In Independent House For Sale In Elect...,"Independent House, Hosur Rd,Near Infosys Limited","1,200 sqft"
11,4 BHK Apartment For Sale In Gopalan Gardenia...,"Gopalan Gardenia Gopalan gardenia, Veerasandr...","2,650 sqft"
12,4 BHK For Sale In Gpr Royale In Gpr Royale,6th Cross,"3,100 sqft"
13,4 BHK Flat For Sale In Heena Enclave In Elec...,"Neeladri Nagar,Near Pioneer Sun Blossom","2,350 sqft"
14,4 BHK For Sale In Deccan Palms Park In Electr...,"Deccan Palms Park Deccan Palms Villas, Deccan...","3,000 sqft"
15,4 BHK In Independent House For Sale In Elect...,"Independent House, Industrial Area Near Tech M...","1,500 sqft"

In [62]:
# programme to scrape the details from dineout.co.in

In [63]:
url = 'https://www.dineout.co.in/delhi-restaurants/buffet-special'
page = requests.get(url)

In [64]:
bs6 = BeautifulSoup(page.content,'html.parser')

In [65]:
Resturant = []
r = bs6.find_all('a' , class_ = 'restnt-name ellipsis')
for data in r:
    res = data.text
    Resturant.append(res)
Resturant

['Castle Barbeque',
 'Jungle Jamboree',
 'Castle Barbeque',
 'Cafe Knosh',
 'The Barbeque Company',
 'India Grill',
 'Delhi Barbeque',
 'The Monarch - Bar Be Que Village',
 'World Cafe',
 'Indian Grill Room',
 'Mad 4 Bar B Que',
 'Barbeque 29',
 'Glasshouse']

In [66]:
cuisine = []
c = bs6.find_all('span', class_ = 'double-line-ellipsis')
for data in c:
    cui = data.text.split('|')[1]
    cuisine.append(cui)
cuisine

[' Chinese, North Indian',
 ' North Indian, Barbecue, Italian, Asian',
 ' North Indian, Chinese',
 ' Multi-Cuisine, North Indian, Italian, Continental, Mediterranean',
 ' Barbecue, Chinese, Mughlai, North Indian',
 ' North Indian, Italian, Oriental ',
 ' Barbecue, North Indian',
 ' North Indian, Chinese, Fast Food',
 ' North Indian, Chinese, Continental',
 ' North Indian, Mughlai, Barbecue',
 ' North Indian, Mughlai',
 ' North Indian, Chinese, Barbecue',
 ' Multi-Cuisine, Asian, European, Italian, North Indian']

In [67]:
Location1 = []
l = bs6.find_all('div', class_ = 'restnt-loc ellipsis')
for data in l:
    lo = data.text
    Location1.append(lo)
Location1

['Connaught Place, Central Delhi',
 '3CS Mall,Lajpat Nagar - 3, South Delhi',
 'Pacific Mall,Tagore Garden, West Delhi',
 'The Leela Ambience Convention Hotel,Shahdara, East Delhi',
 'Gardens Galleria,Sector 38A, Noida',
 'Hilton Garden Inn,Saket, South Delhi',
 'Taurus Sarovar Portico,Mahipalpur, South Delhi',
 'Indirapuram Habitat Centre,Indirapuram, Ghaziabad',
 'Vibe by The Lalit Traveller,Sector 35, Faridabad',
 'Suncity Business Tower,Golf Course Road, Gurgaon',
 'Sector 29, Faridabad',
 'NIT, Faridabad',
 'DoubleTree By Hilton Gurugram Baani Square,Sector 50, Gurgaon']

In [68]:
Ratings = []
r1 = bs6.find_all('div', class_ = 'restnt-rating rating-4')
for data in r1:
    rat = data.text
    Ratings.append(rat)
Ratings

['3.5',
 '3.9',
 '4',
 '4.3',
 '4.1',
 '3.9',
 '3.6',
 '3.9',
 '4.2',
 '4.3',
 '3.9',
 '4.2',
 '4.1']

In [69]:
images = []
for data in bs6.find_all('img' , class_ = 'no-img'):
    images.append(data['data-src'])
images

['https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/k/b/p86792-16062953735fbe1f4d3fb7e.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/a/k/p59633-16046474755fa4fa33c0e92.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/j/o/p38113-15959192065f1fcb666130c.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/4/j/v/p406-163401663361651d79326d0.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/7/q/d/p79307-16051787075fad15532bd7c.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/v/t/p2687-1482477169585cce712b90f.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/v/f/p52501-16006856545f68865616659.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/n/o/p34822-15599107305cfa594a13c24.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/1/p/y/p12366-1466935020576fa6ecdc359.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/y/y/p549-15143767525a438e30b3e19.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/4/j/e/p43488-15295778165b2b8158ceeef.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/w/r/p58842-15624171585d209806d9143.jpg?tr=tr:n-medium',
 'https://im1.dineout.co.in/images/uploads/restaurant/sharpen/9/m/f/p9875-16057921085fb6716cc44f8.jpg?tr=tr:n-medium']

In [70]:
df = pd.DataFrame({'Resturant_Name' : Resturant , 'Cuisine' : cuisine , 'Location' : Location1 , 'Rating' : Ratings, 'Images' : images})
df

,Resturant_Name,Cuisine,Location,Rating,Images
0,Castle Barbeque,"Chinese, North Indian","Connaught Place, Central Delhi",3.5,https://im1.dineout.co.in/images/uploads/resta...
1,Jungle Jamboree,"North Indian, Barbecue, Italian, Asian","3CS Mall,Lajpat Nagar - 3, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
2,Castle Barbeque,"North Indian, Chinese","Pacific Mall,Tagore Garden, West Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
3,Cafe Knosh,"Multi-Cuisine, North Indian, Italian, Contine...","The Leela Ambience Convention Hotel,Shahdara, ...",4.3,https://im1.dineout.co.in/images/uploads/resta...
4,The Barbeque Company,"Barbecue, Chinese, Mughlai, North Indian","Gardens Galleria,Sector 38A, Noida",4.1,https://im1.dineout.co.in/images/uploads/resta...
5,India Grill,"North Indian, Italian, Oriental","Hilton Garden Inn,Saket, South Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
6,Delhi Barbeque,"Barbecue, North Indian","Taurus Sarovar Portico,Mahipalpur, South Delhi",3.6,https://im1.dineout.co.in/images/uploads/resta...
7,The Monarch - Bar Be Que Village,"North Indian, Chinese, Fast Food","Indirapuram Habitat Centre,Indirapuram, Ghaziabad",3.9,https://im1.dineout.co.in/images/uploads/resta...
8,World Cafe,"North Indian, Chinese, Continental","Vibe by The Lalit Traveller,Sector 35, Faridabad",4.2,https://im1.dineout.co.in/images/uploads/resta...
9,Indian Grill Room,"North Indian, Mughlai, Barbecue","Suncity Business Tower,Golf Course Road, Gurgaon",4.3,https://im1.dineout.co.in/images/uploads/resta...
10,Mad 4 Bar B Que,"North Indian, Mughlai","Sector 29, Faridabad",3.9,https://im1.dineout.co.in/images/uploads/resta...
11,Barbeque 29,"North Indian, Chinese, Barbecue","NIT, Faridabad",4.2,https://im1.dineout.co.in/images/uploads/resta...
12,Glasshouse,"Multi-Cuisine, Asian, European, Italian, Nort...","DoubleTree By Hilton Gurugram Baani Square,Sec...",4.1,https://im1.dineout.co.in/images/uploads/resta...

In [71]:
# programme to scrape weather details from Tutiempo.net

In [ ]:
!pip install --upgrade certifi

In [ ]:
!pip install --trusted-host pypi.org --trusted-host pypi.python.org -- trusted-host files.pythonhosted.org pip setuptools

In [74]:
url = 'https://en.tutiempo.net/delhi.html?data=last-24-hours'

In [ ]:
page = requests.get(url)

In [ ]:
# programme to scrape monument name , monument description and Image url

In [76]:
url = 'https://www.puredestinations.co.uk/top-10-famous-monuments-to-visit-in-india/'
page = requests.get(url)

In [77]:
bs7 = BeautifulSoup(page.content,'html.parser')

In [78]:
monument = []
mon = bs7.find_all('strong')
for data in mon:
    mo = data.text
    monument.append(mo)
monument

['Taj Mahal, Agra',
 'Golden Temple (Harmandir Sahib), Amritsar ',
 'Meenakshi Temple, Madurai',
 'Mysore Palace, Mysore',
 'Gateway of India, Mumbai',
 'Red Fort, New Delhi',
 'Hawa Mahal, Jaipur',
 'Qutub Minar, New Delhi',
 'Sanchi Stupa, Sanchi',
 'Charminar, Hyderabad',
 'Things to know before planning your trip to India']

In [79]:
des = []
de = bs7.find_all('p')
for data in de:
    d = data.text
    des.append(d)
des[4:34]

['Taj Mahal, Agra',
 'Enlisted in the Seven Wonders of the World, The Taj Mahal is one of the most beautiful and famous buildings located in the city of Agra. This white marble monument was built by a Mughal Emperor called Shahajahan in memory of his beloved wife. Due to its amazing architecture and the history behind it, this world heritage site has become very popular to visit by all travellers and romantics from all over the world.',
 '',
 'Golden Temple (Harmandir Sahib), Amritsar ',
 'The holiest shrine and pilgrimage place located in Amritsar is The Golden Temple known as the Harmandir Sahib. This is the most famous and sacred Sikh Gurdwara in Punjab, India, adorned with rich history and gold gilded exterior. If you are interested in culture and history, be sure to visit this popular attraction in India.',
 '',
 'Meenakshi Temple, Madurai',
 'Meenakshi Temple is situated on the Southern banks of Vaigai River in the temple city Madurai. This temple is dedicated to Parvati and her consort, Shiva and is visited by most Hindu and Tamil devotees and architectural lovers throughout the world. It is believed that this shrine houses 33,000 sculptures in its 14 gopurams. It’s no doubt one place to visit if you are impressed with art and cultural history.',
 '',
 'Mysore Palace, Mysore',
 'The Mysore Palace is a famous historical monument in the city of Mysore in Karnataka. Commonly described as the City of Palaces, this is the most famous tourist attraction in India after the Taj Mahal. It is a sight not be missed with its spacious halls, lovely art paintings and Indo-Saracenic style architecture. Best time to visit is at night due to the astonishing illuminated lights covering the whole monument.',
 '',
 'Gateway of India, Mumbai',
 'Even though Mumbai is famous for its Bollywood actors and movies, the most famous attraction in Mumbai is The Gateway of India. It is a popular gathering spot for locals, travellers, street vendors and photographers and is known as the Taj Mahal of Mumbai. The majestic monument was built to commemorate the visit of King George V and Queen Mary to Bombay. With so much fun and excitement this place is not to be missed with family or on your tour of India.',
 '',
 'Red Fort, New Delhi',
 'Declared as the UNESCO’s World Heritage Site, Red Fort is located in the centre of beautiful Delhi. If you love learning about history and culture then this famous historic monument is a must see place to visit. Built by the Mughal Emperor, Shah Jahan in 1648, and housing a number of museums, its walls are built of red sandstone. The best time to visit is on Independence Day where the Prime Minister of India hoists the national flag at the Red Fort. End the day by heading to an Indian restaurant and enjoy the varieties of wonderful cuisines.',
 '',
 'Hawa Mahal, Jaipur',
 'Explore a blend of beauty and Rajasthan culture, the Hawa Mahal also known as Palace of Winds is situated in the capital of Rajasthan, Jaipur. Built from red and pink sandstones by the Maharaja Sawi Pratap Singh in 1799, this unique five storey structure is one of the most prominent tourist attractions in the Jaipur city.',
 '',
 'Qutub Minar, New Delhi',
 'Discover one of the tallest towers in the world and the second tallest Minar of India standing elegantly in the Capital city, New Delhi. Standing at 72.5 metres and consisting of around 379 stairs, this famous monument represents the rich architecture of India. As it is a UNESCO World Heritage Site made of red sandstone and decorated with Arabic and Brahmi inscriptions, travellers from around the world come to view this most famous tower in India.',
 '',
 'Sanchi Stupa, Sanchi',
 'The beautiful and massive dome, Sanchi Stupa also known as the Great Stupa is a world renowned Buddhist monument in Sanchi, India. It was constructed by Emperor Ashoka, and is one of the oldest stone structures in the heart of India. Experience the Indian culture by visiting these major attractions in Sanchi including a number of Buddhist Stupas, monasteries and temples.',
 '',
 'Charminar, Hyderabad',
 'No visit to Hyderabad should be complete without visiting the most famous and majestic monument known as the Charminar. This magnificent and striking mosque constructed in 1591 has four minarets and is the most recognisable symbol in the city of Hyderabad.',
 '']

In [ ]:
ima = []
for data in bs7.find_all('img', class_ = 'taj-mahal-pd-blog'):
    ima.append(data['data-src'])
ima